services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    volumes:
      - ~/mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=farmacia
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=069420
    ports:
      - "27017:27017"